# Generated by Django 2.1.5 on 2019-01-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('last_arrival', models.DateTimeField(null=True)),
                ('last_update', models.DateTimeField(null=True)),
                ('arrival_interval', models.DurationField()),
                ('is_active', models.BooleanField()),
                ('status', models.TextField(default='')),
                ('notes', models.TextField(default='')),
                ('monitor_loaded', models.BooleanField(default=True)),
                ('group_name', models.CharField(max_length=200)),
            ],
        ),
    ]
